baseURL = "https://mcclain.sh/"
languageCode = "en-us"
title = "mcclain.sh"
theme = "hermit"

googleAnalytics = "UA-131000305-1"

[author]
    name = "Brian McClain"

[params]

    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "Jan 2, 2006 3:04 PM"

    [[params.social]]
        name = "twitter"
        url = "https://twitter.com/BrianMMcClain"

    [[params.social]]
        name = "github"
        url = "https://github.com/brianmmcclain"

    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/brian-mcclain/"
    
[menu]
    
    [[menu.main]]
        name = "Posts"
        url = "/posts"
        weight = 10
    
    [[menu.main]]
        name = "About"
        url = "/about"
        weight = 20