baseURL = 'https://mcclain.sh/'
languageCode = 'en-us'
languageName = "English"
title = 'mcclain.sh'
theme = "LoveIt"

[author]
  name = "Brian McClain"
  email = ""
  link = "/brian"


[params.social]
    [params.social.GitHub]
        id = "BrianMMcClain"
        weight = 2
    [params.social.youtubelegacy]
        id = "brianmmcclain"
        weight = 3
    [params.social.LinkedIn]
        id = "brian-mcclain"
        weight = 4

[params]
    defaultTheme = "dark"
    title = "mcclain.sh"
    images = ['/images/site-default.png']
    description = "Welcome to mcclain.sh"
    [params.header]
        [params.header.title]
            name = "mcclain.sh"
    [params.app]
        title = "mcclain.sh"
    [params.author]
        name = "Brian McClain"
    [params.home]
        [params.home.profile]
            enable = true
            gravatarEmail = "brianmmcclain@gmail.com"
            title = "mcclain.sh"
            subtitle = ""
    [params.page]
        [params.page.share]
            HackerNews = false
            Line = false
            Weibo = false
            Linkedin = true
        [params.page.code]
            maxShownLines = 80
    [params.analytics]
        enable = true
        [params.analytics.google]
            id = "UA-131000305-1"


[menu]
    [[menu.main]]
        weight = 1
        identifier = "brian"
        name = "About Me"
        url = "/brian/"
        title = ""
    [[menu.main]]
        weight = 2
        identifier = "posts"
        name = "Posts"
        url = "/posts/"



[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
